import websiteSettingsListeners from "./websiteSettingsListeners";
import potentialClientListeners from "./potentialClientListeners";
import InstallationListeners from "./installationListeners";
import productionListeners from "./productionListeners";
import supplierListeners from "./supplierListeners";
import scheduleListeners from "./scheduleListeners";
import settingsListeners from "./settingsListeners";
import archiveListeners from "./archiveListeners";
import productListeners from "./productListeners";
import projectListeners from "./projectListeners";
import clientListeners from "./clientListeners";
import orderListeners from "./orderListeners";
import userListeners from "./userListeners";
import gateListeners from "./gateListeners";
import { Socket } from "socket.io-client";

export default (socket: Socket) => {
  websiteSettingsListeners(socket);
  potentialClientListeners(socket);
  InstallationListeners(socket);
  productionListeners(socket);
  supplierListeners(socket);
  settingsListeners(socket);
  scheduleListeners(socket);
  archiveListeners(socket);
  productListeners(socket);
  projectListeners(socket);
  clientListeners(socket);
  orderListeners(socket);
  userListeners(socket);
  gateListeners(socket);
};
